# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jayesh/Documents/Unfolding

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jayesh/Documents/Unfolding

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayesh/Documents/Unfolding/CMakeFiles /home/jayesh/Documents/Unfolding//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayesh/Documents/Unfolding/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources

# Build rule for target.
CGAL_Qt5_moc_and_resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources
.PHONY : CGAL_Qt5_moc_and_resources

# fast build rule for target.
CGAL_Qt5_moc_and_resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build
.PHONY : CGAL_Qt5_moc_and_resources/fast

#=============================================================================
# Target rules for targets named gradient.out

# Build rule for target.
gradient.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gradient.out
.PHONY : gradient.out

# fast build rule for target.
gradient.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradient.out.dir/build.make CMakeFiles/gradient.out.dir/build
.PHONY : gradient.out/fast

#=============================================================================
# Target rules for targets named display

# Build rule for target.
display: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 display
.PHONY : display

# fast build rule for target.
display/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/display.dir/build.make CMakeFiles/display.dir/build
.PHONY : display/fast

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources_autogen

# Build rule for target.
CGAL_Qt5_moc_and_resources_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources_autogen
.PHONY : CGAL_Qt5_moc_and_resources_autogen

# fast build rule for target.
CGAL_Qt5_moc_and_resources_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build
.PHONY : CGAL_Qt5_moc_and_resources_autogen/fast

#=============================================================================
# Target rules for targets named freeglut

# Build rule for target.
freeglut: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freeglut
.PHONY : freeglut

# fast build rule for target.
freeglut/fast:
	$(MAKE) $(MAKESILENT) -f Tutorial/gltut/glsdk/CMakeFiles/freeglut.dir/build.make Tutorial/gltut/glsdk/CMakeFiles/freeglut.dir/build
.PHONY : freeglut/fast

#=============================================================================
# Target rules for targets named glload

# Build rule for target.
glload: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glload
.PHONY : glload

# fast build rule for target.
glload/fast:
	$(MAKE) $(MAKESILENT) -f Tutorial/gltut/glsdk/CMakeFiles/glload.dir/build.make Tutorial/gltut/glsdk/CMakeFiles/glload.dir/build
.PHONY : glload/fast

#=============================================================================
# Target rules for targets named glimg

# Build rule for target.
glimg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glimg
.PHONY : glimg

# fast build rule for target.
glimg/fast:
	$(MAKE) $(MAKESILENT) -f Tutorial/gltut/glsdk/CMakeFiles/glimg.dir/build.make Tutorial/gltut/glsdk/CMakeFiles/glimg.dir/build
.PHONY : glimg/fast

#=============================================================================
# Target rules for targets named glutil

# Build rule for target.
glutil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glutil
.PHONY : glutil

# fast build rule for target.
glutil/fast:
	$(MAKE) $(MAKESILENT) -f Tutorial/gltut/glsdk/CMakeFiles/glutil.dir/build.make Tutorial/gltut/glsdk/CMakeFiles/glutil.dir/build
.PHONY : glutil/fast

#=============================================================================
# Target rules for targets named framework

# Build rule for target.
framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework
.PHONY : framework

# fast build rule for target.
framework/fast:
	$(MAKE) $(MAKESILENT) -f Tutorial/gltut/framework/CMakeFiles/framework.dir/build.make Tutorial/gltut/framework/CMakeFiles/framework.dir/build
.PHONY : framework/fast

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o

# target to build an object file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i

# target to preprocess a source file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s

# target to generate assembly for a file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s

Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.o: Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.o
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.o

# target to build an object file
Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/display.dir/build.make CMakeFiles/display.dir/Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.o
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.o

Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.i: Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.i
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.i

# target to preprocess a source file
Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/display.dir/build.make CMakeFiles/display.dir/Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.i
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.i

Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.s: Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.s
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.s

# target to generate assembly for a file
Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/display.dir/build.make CMakeFiles/display.dir/Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.s
.PHONY : Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.cpp.s

gradient.o: gradient.cpp.o
.PHONY : gradient.o

# target to build an object file
gradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradient.out.dir/build.make CMakeFiles/gradient.out.dir/gradient.cpp.o
.PHONY : gradient.cpp.o

gradient.i: gradient.cpp.i
.PHONY : gradient.i

# target to preprocess a source file
gradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradient.out.dir/build.make CMakeFiles/gradient.out.dir/gradient.cpp.i
.PHONY : gradient.cpp.i

gradient.s: gradient.cpp.s
.PHONY : gradient.s

# target to generate assembly for a file
gradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gradient.out.dir/build.make CMakeFiles/gradient.out.dir/gradient.cpp.s
.PHONY : gradient.cpp.s

qrc_CGAL.o: qrc_CGAL.cpp.o
.PHONY : qrc_CGAL.o

# target to build an object file
qrc_CGAL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.o
.PHONY : qrc_CGAL.cpp.o

qrc_CGAL.i: qrc_CGAL.cpp.i
.PHONY : qrc_CGAL.i

# target to preprocess a source file
qrc_CGAL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.i
.PHONY : qrc_CGAL.cpp.i

qrc_CGAL.s: qrc_CGAL.cpp.s
.PHONY : qrc_CGAL.s

# target to generate assembly for a file
qrc_CGAL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.s
.PHONY : qrc_CGAL.cpp.s

qrc_File.o: qrc_File.cpp.o
.PHONY : qrc_File.o

# target to build an object file
qrc_File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.o
.PHONY : qrc_File.cpp.o

qrc_File.i: qrc_File.cpp.i
.PHONY : qrc_File.i

# target to preprocess a source file
qrc_File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.i
.PHONY : qrc_File.cpp.i

qrc_File.s: qrc_File.cpp.s
.PHONY : qrc_File.s

# target to generate assembly for a file
qrc_File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.s
.PHONY : qrc_File.cpp.s

qrc_Input.o: qrc_Input.cpp.o
.PHONY : qrc_Input.o

# target to build an object file
qrc_Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.o
.PHONY : qrc_Input.cpp.o

qrc_Input.i: qrc_Input.cpp.i
.PHONY : qrc_Input.i

# target to preprocess a source file
qrc_Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.i
.PHONY : qrc_Input.cpp.i

qrc_Input.s: qrc_Input.cpp.s
.PHONY : qrc_Input.s

# target to generate assembly for a file
qrc_Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.s
.PHONY : qrc_Input.cpp.s

qrc_Triangulation_2.o: qrc_Triangulation_2.cpp.o
.PHONY : qrc_Triangulation_2.o

# target to build an object file
qrc_Triangulation_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.o
.PHONY : qrc_Triangulation_2.cpp.o

qrc_Triangulation_2.i: qrc_Triangulation_2.cpp.i
.PHONY : qrc_Triangulation_2.i

# target to preprocess a source file
qrc_Triangulation_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.i
.PHONY : qrc_Triangulation_2.cpp.i

qrc_Triangulation_2.s: qrc_Triangulation_2.cpp.s
.PHONY : qrc_Triangulation_2.s

# target to generate assembly for a file
qrc_Triangulation_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.s
.PHONY : qrc_Triangulation_2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CGAL_Qt5_moc_and_resources_autogen"
	@echo "... CGAL_Qt5_moc_and_resources"
	@echo "... display"
	@echo "... framework"
	@echo "... freeglut"
	@echo "... glimg"
	@echo "... glload"
	@echo "... glutil"
	@echo "... gradient.out"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s"
	@echo "... Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.o"
	@echo "... Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.i"
	@echo "... Tut_03_OpenGLs_Moving_Triangle/CPUPositionOffset.s"
	@echo "... gradient.o"
	@echo "... gradient.i"
	@echo "... gradient.s"
	@echo "... qrc_CGAL.o"
	@echo "... qrc_CGAL.i"
	@echo "... qrc_CGAL.s"
	@echo "... qrc_File.o"
	@echo "... qrc_File.i"
	@echo "... qrc_File.s"
	@echo "... qrc_Input.o"
	@echo "... qrc_Input.i"
	@echo "... qrc_Input.s"
	@echo "... qrc_Triangulation_2.o"
	@echo "... qrc_Triangulation_2.i"
	@echo "... qrc_Triangulation_2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

